### ISSUE TITLE
How to use FindAndRemove()

### ISSUE THREAD

**Issue by LeMoussel** [khalidsalomao/SimpleHelpers.Net#4]
Hi,
Can you explain how to r emoves all items that meets the search parameters with `FindAndRemove()` method?

for example
````C#
// Get first inserted row
var row = _sqliteStorageDB.Get().FirstOrDefault();
// Find & Remove this row
_sqliteStorageDB.FindAndRemove( "row. How to do it?");
````
Thanks

**Comment by khalidsalomao** [comment]
Hi @LeMoussel,

The recommended way is to use the same key used to store the item, since it will use a database index (best performance).


So, if you have a key that was used to store the inserted row, you can pass it as the first parameter:

```
// save an item with a key associated
db.Set ("my_key_for_this_item", new MyExampleClass ());

// remove it
db.FindAndRemove ("my_key_for_this_item", null);
```

Usually I recommend to store the key with the object, to make things easier!

Example:

```
var row = new MyExampleRow ();
row.Id = "my_key_for_this_item";

// save an item with a key associated
db.Set (row.Id, row);

// remove it
db.FindAndRemove (row.Id, null);
```


There are other uses, but uses the `LIKE` sql expression to remove rows. This is slow, since is not using an index, and may have undesirable consequences, so only use it if you know what is happening behind the scenes!

Example:

```
var user = new MyExampleUser ();
row.Id = "my_key_for_this_item";
row.Name = "my name";
row.Password = "*******";

// save an item with a key associated
db.Set (row.Id, row);

// remove it by name
db.FindAndRemove (null, new { Name = "my name" });

// OR remove it by key and name
db.FindAndRemove ("my_key_for_this_item", new { Name = "my name" });
```
